// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"
)

const createComment = `-- name: CreateComment :execlastid
INSERT INTO task_comments (task_id, user_id, content)
VALUES (?, ?, ?)
`

type CreateCommentParams struct {
	TaskID  uint64 `json:"task_id"`
	UserID  uint64 `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createComment, arg.TaskID, arg.UserID, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT id, task_id, user_id, content, created_at
FROM task_comments
WHERE task_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTaskComments(ctx context.Context, taskID uint64) ([]TaskComment, error) {
	rows, err := q.db.QueryContext(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
