// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"
)

const createTaskHistory = `-- name: CreateTaskHistory :execlastid
INSERT INTO task_history (task_id, changed_by, changes)
VALUES (?, ?, ?)
`

type CreateTaskHistoryParams struct {
	TaskID    uint64 `json:"task_id"`
	ChangedBy uint64 `json:"changed_by"`
	Changes   string `json:"changes"`
}

func (q *Queries) CreateTaskHistory(ctx context.Context, arg CreateTaskHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTaskHistory, arg.TaskID, arg.ChangedBy, arg.Changes)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listTaskHistory = `-- name: ListTaskHistory :many
SELECT id, task_id, changed_by, changes, created_at
FROM task_history
WHERE task_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTaskHistory(ctx context.Context, taskID uint64) ([]TaskHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskHistory{}
	for rows.Next() {
		var i TaskHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChangedBy,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
