// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)
FROM tasks
WHERE team_id = ?
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR assignee_id = ?)
`

type CountTasksParams struct {
	TeamID     uint64          `json:"team_id"`
	Status     NullTasksStatus `json:"status"`
	AssigneeID sql.NullInt64   `json:"assignee_id"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks,
		arg.TeamID,
		arg.Status,
		arg.Status,
		arg.AssigneeID,
		arg.AssigneeID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :execlastid
INSERT INTO tasks (team_id, title, description, status, created_by, assignee_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	TeamID      uint64        `json:"team_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      TasksStatus   `json:"status"`
	CreatedBy   uint64        `json:"created_by"`
	AssigneeID  sql.NullInt64 `json:"assignee_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.AssigneeID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, team_id, title, description, status, created_by, assignee_id,
       created_at, updated_at, closed_at, version
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id uint64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Version,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, team_id, title, description, status, created_by, assignee_id,
       created_at, updated_at, closed_at, version
FROM tasks
WHERE team_id = ?
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR assignee_id = ?)
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListTasksParams struct {
	TeamID     uint64          `json:"team_id"`
	Status     NullTasksStatus `json:"status"`
	AssigneeID sql.NullInt64   `json:"assignee_id"`
	Limit      int32           `json:"limit"`
	Offset     int32           `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.TeamID,
		arg.Status,
		arg.Status,
		arg.AssigneeID,
		arg.AssigneeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET title       = ?,
    description = ?,
    status      = ?,
    assignee_id = ?,
    closed_at   = ?,
    updated_at  = CURRENT_TIMESTAMP,
    version     = version + 1
WHERE id = ? AND version = ?
`

type UpdateTaskParams struct {
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      TasksStatus   `json:"status"`
	AssigneeID  sql.NullInt64 `json:"assignee_id"`
	ClosedAt    sql.NullTime  `json:"closed_at"`
	ID          uint64        `json:"id"`
	Version     uint32        `json:"version"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeID,
		arg.ClosedAt,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
