// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
	"time"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES (?, ?, ?)
`

type AddTeamMemberParams struct {
	TeamID uint64          `json:"team_id"`
	UserID uint64          `json:"user_id"`
	Role   TeamMembersRole `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const countTeamOwners = `-- name: CountTeamOwners :one
SELECT COUNT(*)
FROM team_members
WHERE team_id = ? AND role = 'owner'
`

func (q *Queries) CountTeamOwners(ctx context.Context, teamID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamOwners, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :execlastid
INSERT INTO teams (name, created_by)
VALUES (?, ?)
`

type CreateTeamParams struct {
	Name      string `json:"name"`
	CreatedBy uint64 `json:"created_by"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTeam, arg.Name, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_by, created_at
FROM teams
WHERE id = ?
`

func (q *Queries) GetTeamByID(ctx context.Context, id uint64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role, created_at
FROM team_members
WHERE team_id = ? AND user_id = ?
`

type GetTeamMemberParams struct {
	TeamID uint64 `json:"team_id"`
	UserID uint64 `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMemberForUpdate = `-- name: GetTeamMemberForUpdate :one
SELECT team_id, user_id, role, created_at
FROM team_members
WHERE team_id = ? AND user_id = ?
FOR UPDATE
`

type GetTeamMemberForUpdateParams struct {
	TeamID uint64 `json:"team_id"`
	UserID uint64 `json:"user_id"`
}

func (q *Queries) GetTeamMemberForUpdate(ctx context.Context, arg GetTeamMemberForUpdateParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberForUpdate, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id AS user_id, u.email, u.name, tm.role, tm.created_at
FROM team_members tm
         JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = ?
ORDER BY tm.created_at ASC, u.id ASC
`

type ListTeamMembersRow struct {
	UserID    uint64          `json:"user_id"`
	Email     string          `json:"email"`
	Name      string          `json:"name"`
	Role      TeamMembersRole `json:"role"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uint64) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.created_by, t.created_at
FROM teams t
         JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = ?
ORDER BY t.created_at DESC, t.id DESC
`

func (q *Queries) ListUserTeams(ctx context.Context, userID uint64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members
WHERE team_id = ? AND user_id = ?
`

type RemoveTeamMemberParams struct {
	TeamID uint64 `json:"team_id"`
	UserID uint64 `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :execrows
UPDATE team_members
SET role = ?
WHERE team_id = ? AND user_id = ?
`

type UpdateTeamMemberRoleParams struct {
	Role   TeamMembersRole `json:"role"`
	TeamID uint64          `json:"team_id"`
	UserID uint64          `json:"user_id"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTeamMemberRole, arg.Role, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
